[psql]
  dbname = "sample_db"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  sslmode= "disable"
  blacklist = []

[[types]]
  [types.match]
    type = "null.Time"
    nullable = true

  [types.replace]
    type = "mytypes.NullTime"

  [types.imports]
    third_party = ['mytypes "github.com/uhey22e/sqlboiler-tutor/types"']

